[package]
name = "ticket-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
tokio = { version = "1.49.0", features = ["rt-multi-thread"] }
anyhow = "1.0.102"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }