[package]
name = "whatsapp-trt"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
serde = "1.0.228"
tokio = { version = "1.49.0", features = ["rt-multi-thread"] }
clap = { version = "4.5.6", features = ["derive"] }
anyhow = "1.0.102"